spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://dpg-d6viaqfkijhs73cscdtg-a.oregon-postgres.render.com:5432/gojoblesdb}
    username: ${DATABASE_USERNAME:gojoblesdb_user}
    password: ${DATABASE_PASSWORD:05iPuw1e8bqGzbyj5UkjEnq7OoEyT2EZ}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 1 day

youtube:
  api:
    key: ${YOUTUBE_API_KEY:AIzaSyAv6_jqtdOJInpgRkwNhO7sOWwQflvZxOA}
